-- Add more challenges to the database for better variety
-- Run this in your Supabase SQL Editor

INSERT INTO challenges (description) VALUES
    -- Social Interaction Challenges
    ('Get someone to say "I don''t know"'),
    ('Convince someone you''re from another country'),
    ('Make someone compliment your outfit'),
    ('Get someone to tell you a secret'),
    ('Make someone laugh so hard they snort'),
    ('Get someone to high-five you'),
    ('Make someone say "wow"'),
    ('Get someone to share their favorite food'),
    ('Make someone do a double-take'),
    ('Get someone to ask you a question'),
    
    -- Physical Challenges
    ('Do 10 jumping jacks without anyone noticing'),
    ('Touch your toes and hold for 5 seconds'),
    ('Spin around 3 times and act dizzy'),
    ('Do your best robot dance move'),
    ('Pretend to be a statue for 30 seconds'),
    ('Walk backwards for 10 steps'),
    ('Do a cartwheel or attempt one'),
    ('Balance something on your head for 1 minute'),
    ('Do your best superhero pose'),
    ('Pretend to be invisible for 2 minutes'),
    
    -- Communication Challenges
    ('Speak in a different accent for 5 minutes'),
    ('Use only questions to communicate for 3 minutes'),
    ('Talk like a pirate for 2 minutes'),
    ('Speak in rhymes for 1 minute'),
    ('Use only movie quotes to respond for 5 minutes'),
    ('Talk like a robot for 3 minutes'),
    ('Speak in a whisper for 2 minutes'),
    ('Use only one word responses for 5 minutes'),
    ('Talk like you''re underwater'),
    ('Speak in slow motion for 1 minute'),
    
    -- Observation Challenges
    ('Find something red in the room'),
    ('Count how many people are wearing blue'),
    ('Find something that starts with the letter "M"'),
    ('Notice something no one else has noticed'),
    ('Find the most interesting object in the room'),
    ('Count all the windows in the building'),
    ('Find something that''s older than you'),
    ('Notice someone''s unique feature and compliment it'),
    ('Find something that makes a sound'),
    ('Discover something new about the space'),
    
    -- Creative Challenges
    ('Make up a story about the person next to you'),
    ('Create a new dance move and teach it to someone'),
    ('Invent a new handshake'),
    ('Make up a nickname for someone'),
    ('Create a secret code with someone'),
    ('Invent a new sport and explain the rules'),
    ('Make up a conspiracy theory about the room'),
    ('Create a new holiday and explain how to celebrate it'),
    ('Invent a new superhero and describe their powers'),
    ('Make up a new language and speak it for 1 minute'),
    
    -- Memory Challenges
    ('Remember everyone''s name in the room'),
    ('Memorize a phone number someone gives you'),
    ('Remember what everyone is wearing'),
    ('Memorize a short poem someone recites'),
    ('Remember the order of people in a line'),
    ('Memorize a shopping list someone gives you'),
    ('Remember everyone''s favorite color'),
    ('Memorize a sequence of numbers'),
    ('Remember what everyone had for breakfast'),
    ('Memorize a short story someone tells you'),
    
    -- Problem Solving Challenges
    ('Solve a riddle someone gives you'),
    ('Figure out how to open a locked box'),
    ('Find a way to reach something high up'),
    ('Solve a math problem in your head'),
    ('Figure out how to make something float'),
    ('Find a creative use for a paperclip'),
    ('Solve a word puzzle'),
    ('Figure out how to balance 3 objects'),
    ('Find a way to make music without instruments'),
    ('Solve a logic puzzle'),
    
    -- Emotional Challenges
    ('Make someone feel better when they''re sad'),
    ('Get someone to smile when they''re grumpy'),
    ('Make someone feel special'),
    ('Get someone to laugh when they''re stressed'),
    ('Make someone feel confident'),
    ('Get someone to relax when they''re tense'),
    ('Make someone feel appreciated'),
    ('Get someone to feel excited about something'),
    ('Make someone feel understood'),
    ('Get someone to feel proud of themselves'),
    
    -- Stealth Challenges
    ('Sneak up behind someone without them noticing'),
    ('Take a photo without anyone seeing'),
    ('Eavesdrop on a conversation and remember details'),
    ('Sneak a note to someone without others seeing'),
    ('Hide something and see if anyone finds it'),
    ('Sneak a high-five to someone'),
    ('Secretly organize something in the room'),
    ('Sneak a compliment to someone'),
    ('Secretly help someone without them knowing'),
    ('Sneak a joke into a conversation'),
    
    -- Skill Challenges
    ('Juggle 3 objects for 30 seconds'),
    ('Do a magic trick'),
    ('Sing a song in a different language'),
    ('Do an impression of an animal'),
    ('Show off a hidden talent'),
    ('Do a handstand or attempt one'),
    ('Play an instrument if available'),
    ('Do a backflip or attempt one'),
    ('Show off your flexibility'),
    ('Demonstrate a martial arts move'),
    
    -- Social Engineering Challenges
    ('Get someone to give you their seat'),
    ('Convince someone to share their food'),
    ('Get someone to lend you something'),
    ('Convince someone to join your team'),
    ('Get someone to follow your lead'),
    ('Convince someone to change their mind'),
    ('Get someone to trust you with a secret'),
    ('Convince someone to try something new'),
    ('Get someone to help you with a task'),
    ('Convince someone to make a decision'),
    
    -- Observation and Detail Challenges
    ('Notice someone''s eye color'),
    ('Find something that''s out of place'),
    ('Notice someone''s unique mannerism'),
    ('Find something that''s been moved'),
    ('Notice someone''s mood change'),
    ('Find something that''s broken'),
    ('Notice someone''s nervous habit'),
    ('Find something that''s been forgotten'),
    ('Notice someone''s accent or speech pattern'),
    ('Find something that''s been hidden'),
    
    -- Communication and Language Challenges
    ('Learn a new word and use it in conversation'),
    ('Teach someone a new phrase in another language'),
    ('Use only gestures to communicate for 2 minutes'),
    ('Speak in a different dialect'),
    ('Use only positive words for 5 minutes'),
    ('Communicate using only sounds'),
    ('Use only metaphors to explain something'),
    ('Speak like a news reporter for 2 minutes'),
    ('Use only questions to get information'),
    ('Communicate using only song lyrics'),
    
    -- Physical Coordination Challenges
    ('Walk in a straight line with your eyes closed'),
    ('Catch something thrown to you with one hand'),
    ('Balance on one foot for 1 minute'),
    ('Walk while balancing something on your head'),
    ('Do jumping jacks while counting backwards'),
    ('Walk while patting your head and rubbing your stomach'),
    ('Do a somersault or attempt one'),
    ('Walk on your tiptoes for 30 seconds'),
    ('Do a handstand against a wall'),
    ('Walk while spinning a pen on your finger'),
    
    -- Mental Challenges
    ('Count backwards from 100 by 7s'),
    ('Recite the alphabet backwards'),
    ('Name all the states that start with "M"'),
    ('List 10 words that rhyme with "blue"'),
    ('Name all the colors in a rainbow'),
    ('Count how many words you can make from "SUPERCALIFRAGILISTIC"'),
    ('Name all the planets in order'),
    ('List 5 things you can do with a paperclip'),
    ('Name all the days of the week backwards'),
    ('List 10 animals that start with "C"'),
    
    -- Social Bonding Challenges
    ('Find something in common with everyone in the room'),
    ('Get everyone to agree on something'),
    ('Make everyone laugh at the same time'),
    ('Get everyone to participate in a group activity'),
    ('Make everyone feel included in a conversation'),
    ('Get everyone to share a positive memory'),
    ('Make everyone feel comfortable'),
    ('Get everyone to work together on a task'),
    ('Make everyone feel valued'),
    ('Get everyone to celebrate something together')
ON CONFLICT DO NOTHING; 