-- Clear existing challenges and replace with Missions.txt challenges
DELETE FROM challenges;

-- Insert all challenges from Missions.txt
INSERT INTO challenges (description, category) VALUES
('Get another player to spell any word out loud.', 'Social'),
('Get another player to yawn right after you do.', 'Social'),
('Get another player to say "thank you" to you.', 'Social'),
('Get another player to look up information for you on their phone.', 'Social'),
('Get another player to correct an obviously false statement you make.', 'Social'),
('Get another player to hold your phone for you.', 'Social'),
('Get another player to give you a high-five.', 'Social'),
('Get another player to ask "What?" after you say something to them.', 'Social'),
('Get another player to agree with a ridiculous statement you make.', 'Social'),
('Get another player to say they remember something from the past you bring up.', 'Social'),
('Get another player to ask you what time it is.', 'Social'),
('Get another player to hand you a piece of their food.', 'Social'),
('Get another player to correct your pronunciation of a word.', 'Social'),
('Get another player to say the name of a celebrity.', 'Social'),
('Get another player to shield their eyes from the sun.', 'Social'),
('Get another player to show you a photo on their phone.', 'Social'),
('Get another player to say "bless you" after you fake a sneeze.', 'Social'),
('Get another player to point at something in the sky.', 'Social'),
('Get another player to recommend a movie or TV show to you.', 'Social'),
('Get another player to say the word "literally."', 'Social'),
('Get another player to scratch an itch.', 'Social'),
('Get another player to agree that a certain food is overrated.', 'Social'),
('Get another player to use hand sanitizer.', 'Social'),
('Get another player to look at the bottom of their shoe.', 'Social'),
('Get another player to sing a line from any song.', 'Social'),
('Get another player to say the name of a color.', 'Social'),
('Get another player to adjust their glasses or hair.', 'Social'),
('Get another player to tell you a joke.', 'Social'),
('Get another player to ask if you are okay.', 'Social'),
('Get another player to mention a brand name.', 'Social'),
('Get another player to cross their arms.', 'Social'),
('Get another player to say a number greater than ten.', 'Social'),
('Get another player to let you borrow a pen.', 'Social'),
('Get another player to look inside their own wallet or purse.', 'Social'),
('Get another player to talk about the weather.', 'Social'),
('Get another player to crack their knuckles.', 'Social'),
('Get another player to say your name.', 'Social'),
('Get another player to refer to a pet.', 'Social'),
('Get another player to take a sip of their drink.', 'Social'),
('Get another player to put their phone face down on a table.', 'Social'),
('Get another player to say "I don''t know."', 'Social'),
('Get another player to stretch their arms.', 'Social'),
('Get another player to name a capital city.', 'Social'),
('Get another player to mention something they have to do later.', 'Social'),
('Get another player to check their watch or phone for the time.', 'Social'),
('Get another player to say "I''m tired."', 'Social'),
('Get another player to refer to a family member.', 'Social'),
('Get another player to complain about something.', 'Social'),
('Get another player to laugh at something that wasn''t funny.', 'Social'),
('Get another player to guess your age.', 'Social'),
('Get another player to use a piece of slang correctly.', 'Social'),
('Get another player to say the word "weird."', 'Social'),
('Get another player to offer you advice.', 'Social'),
('Get another player to raise their eyebrows.', 'Social'),
('Get another player to talk about a dream they had.', 'Social'),
('Get another player to take off a jacket or sweater.', 'Social'),
('Get another player to say "that makes sense."', 'Social'),
('Get another player to compliment someone other than you.', 'Social'),
('Get another player to mention a holiday.', 'Social'),
('Get another player to lean back in their chair.', 'Social'),
('Get another player to say the word "actually."', 'Social'),
('Get another player to fold a piece of paper.', 'Social'),
('Get another player to ask for your opinion.', 'Social'),
('Get another player to say something in a different language.', 'Social'),
('Get another player to lock their phone.', 'Social'),
('Get another player to admit they were wrong about something.', 'Social'),
('Get another player to say "oh my god."', 'Social'),
('Get another player to move an object on the table.', 'Social'),
('Get another player to use a movie quote.', 'Social'),
('Get another player to nod in agreement.', 'Social'),
('Get another player to wipe their hands on their pants.', 'Social'),
('Get another player to say "I''m hungry."', 'Social'),
('Get another player to recommend a restaurant.', 'Social'),
('Get another player to tap their fingers on a surface.', 'Social'),
('Get another player to look out a window.', 'Social'),
('Get another player to say "wait."', 'Social'),
('Get another player to name a type of animal.', 'Social'),
('Get another player to say "seriously?"', 'Social'),
('Get another player to rub their eyes.', 'Social'),
('Get another player to say something positive about themselves.', 'Social'),
('Get another player to clean their glasses.', 'Social'),
('Get another player to say the word "maybe."', 'Social'),
('Get another player to ask you to repeat yourself.', 'Social'),
('Get another player to touch their face.', 'Social'),
('Get another player to say the full name of another player.', 'Social'),
('Get another player to talk about their job or school.', 'Social'),
('Get another player to say a word that rhymes with "cat."', 'Social'),
('Get another player to shake their head no.', 'Social'),
('Get another player to say "that''s crazy."', 'Social'),
('Get another player to tell you to be quiet (playfully).', 'Social'),
('Get another player to use a filter on a photo.', 'Social'),
('Get another player to say "I need to..."', 'Social'),
('Get another player to give you directions.', 'Social'),
('Get another player to look at your shoes.', 'Social'),
('Get another player to hum a tune.', 'Social'),
('Get another player to say the word "awesome."', 'Social'),
('Get another player to sit on the floor.', 'Social'),
('Get another player to talk about sports.', 'Social'),
('Get another player to say "I forgot."', 'Social'),
('Get another player to help you look for something you "lost."', 'Social'),
('Get another player to say "good morning" or "good night."', 'Social'),
('Get another player to say a food they dislike.', 'Social'),
('Get another player to put their hands in their pockets.', 'Social'),
('Get another player to say "it''s cold" or "it''s hot."', 'Social'),
('Get another player to use an emoji in a text to you.', 'Social'),
('Get another player to say the word "like" more than three times in one sentence.', 'Social'),
('Get another player to point with their lips or chin.', 'Social'),
('Get another player to say "I''m bored."', 'Social'),
('Get another player to guess a number you''re thinking of.', 'Social'),
('Get another player to roll their eyes.', 'Social'),
('Get another player to say "let''s go."', 'Social'),
('Get another player to say the name of a musical instrument.', 'Social'),
('Get another player to take a selfie.', 'Social'),
('Get another player to say "here you go."', 'Social'),
('Get another player to draw a shape.', 'Social'),
('Get another player to say a word with three syllables.', 'Social'),
('Get another player to talk about social media.', 'Social'),
('Get another player to say "I agree."', 'Social'),
('Get another player to try to do an impression of someone.', 'Social'),
('Get another player to say "for real."', 'Social'),
('Get another player to ask you a question about yourself.', 'Social'),
('Get another player to say the name of a fruit.', 'Social'),
('Get another player to shush someone.', 'Social'),
('Get another player to say "I''m sorry."', 'Social'),
('Get another player to stand on one foot.', 'Social'),
('Get another player to say "that''s hilarious."', 'Social'),
('Get another player to talk about their childhood.', 'Social'),
('Get another player to say the word "whatever."', 'Social'),
('Get another player to open a door for someone.', 'Social'),
('Get another player to say "I''m so full."', 'Social'),
('Get another player to name a type of tree.', 'Social'),
('Get another player to say "I have an idea."', 'Social'),
('Get another player to make a pun.', 'Social'),
('Get another player to say a day of the week.', 'Social'),
('Get another player to talk about a celebrity couple.', 'Social'),
('Get another player to say "you''re right."', 'Social'),
('Get another player to help you with a task.', 'Social'),
('Get another player to say the word "obviously."', 'Social'),
('Get another player to whistle.', 'Social'),
('Get another player to talk about their plans for the weekend.', 'Social'),
('Get another player to say "no way."', 'Social'),
('Get another player to name a brand of car.', 'Social'),
('Get another player to say "good luck."', 'Social'),
('Get another player to show you a video on their phone.', 'Social'),
('Get another player to say "I''m confused."', 'Social'),
('Get another player to snap their fingers.', 'Social'),
('Get another player to name a piece of furniture.', 'Social'),
('Get another player to say "I promise."', 'Social'),
('Get another player to say something sarcastic.', 'Social'),
('Get another player to talk about a recent news event.', 'Social'),
('Get another player to say "oh, interesting."', 'Social'),
('Get another player to clap their hands.', 'Social'),
('Get another player to name a body of water.', 'Social'),
('Get another player to say "I told you so."', 'Social'),
('Get another player to use a hand gesture while talking.', 'Social'),
('Get another player to say the name of a country.', 'Social'),
('Get another player to ask "why?"', 'Social'),
('Get another player to talk about a book.', 'Social'),
('Get another player to say "never mind."', 'Social'),
('Get another player to name a type of clothing.', 'Social'),
('Get another player to say "that''s a good point."', 'Social'),
('Get another player to do a thumbs-up.', 'Social'),
('Get another player to say a month of the year.', 'Social'),
('Get another player to say "I''m excited."', 'Social'),
('Get another player to talk about a personal goal.', 'Social'),
('Get another player to say the word "amazing."', 'Social'),
('Get another player to cover their mouth when they laugh.', 'Social'),
('Get another player to say the word "but."', 'Social'),
('Get another player to name a superhero.', 'Social'),
('Get another player to say "I have to go."', 'Social'),
('Get another player to refer to a fictional character.', 'Social'),
('Get another player to say "are you kidding me?"', 'Social'),
('Get another player to fix something that is crooked.', 'Social'),
('Get another player to name a type of bird.', 'Social'),
('Get another player to say "that''s true."', 'Social'),
('Get another player to help you spell a difficult word.', 'Social'),
('Get another player to say "I love this song."', 'Social'),
('Get another player to talk about a past vacation.', 'Social'),
('Get another player to say the word "definitely."', 'Social'),
('Get another player to look up at the ceiling.', 'Social'),
('Get another player to name a historical figure.', 'Social'),
('Get another player to say "I''m not sure."', 'Social'),
('Get another player to talk about a specific app on their phone.', 'Social'),
('Get another player to say "that''s weird."', 'Social'),
('Get another player to close a tab on their computer or phone.', 'Social'),
('Get another player to say "can you help me?"', 'Social'),
('Get another player to name a type of flower.', 'Social'),
('Get another player to say "I''m proud of you."', 'Social'),
('Get another player to talk about their favorite movie.', 'Social'),
('Get another player to say the word "so."', 'Social'),
('Get another player to pretend to be a character.', 'Social'),
('Get another player to say "it depends."', 'Social'),
('Get another player to name a type of dessert.', 'Social'),
('Get another player to say "I wish."', 'Social'),
('Get another player to talk about their morning routine.', 'Social'),
('Get another player to say "I see."', 'Social'),
('Get another player to pat someone on the back.', 'Social'),
('Get another player to name a tool.', 'Social'),
('Get another player to say "you know what I mean?"', 'Social'),
('Get another player to talk about a current trend.', 'Social'),
('Get another player to say "that''s impressive."', 'Social'),
('Get another player to try and fail to do something.', 'Social'),
('Get another player to say the word "okay."', 'Social'),
('Get another player to name a fast-food chain.', 'Social'),
('Get another player to say "I''m just kidding."', 'Social'),
('Get another player to talk about something they bought recently.', 'Social'),
('Get another player to say "I can''t believe it."', 'Social'),
('Get another player to try a food you offer them.', 'Social'),
('Get another player to name a planet.', 'Social'),
('Get another player to say "let me see."', 'Social'),
('Get another player to talk about a personal fear.', 'Social'),
('Get another player to say "that''s a good question."', 'Social'),
('Get another player to mime an action.', 'Social'),
('Get another player to say the word "actually."', 'Social'),
('Get another player to name a board game.', 'Social'),
('Get another player to say "I''m in."', 'Social'),
('Get another player to talk about their favorite season.', 'Social'),
('Get another player to say "I''ll be right back."', 'Social'),
('Get another player to try to remember someone''s name.', 'Social'),
('Get another player to name a type of sport.', 'Social'),
('Get another player to say "I have no idea."', 'Social'),
('Get another player to talk about a funny memory.', 'Social'),
('Get another player to say "that''s not fair."', 'Social'),
('Get another player to use an acronym in conversation (e.g., LOL, OMG).', 'Social'),
('Get another player to name a type of cheese.', 'Social'),
('Get another player to say "I''m ready."', 'Social'),
('Get another player to talk about their pet peeves.', 'Social'),
('Get another player to say "you''re welcome."', 'Social'),
('Get another player to hide something in their hand.', 'Social'),
('Get another player to name a mythical creature.', 'Social'),
('Get another player to say "I knew it!"', 'Social'),
('Get another player to talk about a talent they have.', 'Social'),
('Get another player to say "that''s enough."', 'Social'),
('Get another player to say a word backwards.', 'Social'),
('Get another player to name a brand of soda.', 'Social'),
('Get another player to say "I''m on my way."', 'Social'),
('Get another player to talk about something they learned recently.', 'Social'),
('Get another player to say "don''t worry about it."', 'Social'),
('Get another player to try to catch something you throw.', 'Social'),
('Get another player to name a cartoon character.', 'Social'),
('Get another player to say "I''m not feeling well."', 'Social'),
('Get another player to talk about a song stuck in their head.', 'Social'),
('Get another player to say "are you serious?"', 'Social'),
('Get another player to move out of someone''s way.', 'Social'),
('Get another player to name a kitchen appliance.', 'Social'),
('Get another player to say "I''ll do it later."', 'Social'),
('Get another player to talk about their dream job.', 'Social'),
('Get another player to say "that''s what she said."', 'Social'),
('Get another player to use a calculator.', 'Social'),
('Get another player to name a famous landmark.', 'Social'),
('Get another player to say "I''m listening."', 'Social'),
('Get another player to talk about something they are looking forward to.', 'Social'),
('Get another player to say "I''m going to..."', 'Social'),
('Get another player to try to solve a riddle you tell them.', 'Social'),
('Get another player to name a shape.', 'Social'),
('Get another player to say "I don''t care."', 'Social'),
('Get another player to talk about their favorite animal.', 'Social'),
('Get another player to say "that''s so cool."', 'Social'),
('Get another player to wipe a surface clean.', 'Social'),
('Get another player to name a type of weather.', 'Social'),
('Get another player to say "I''m almost done."', 'Social'),
('Get another player to talk about a video game.', 'Social'),
('Get another player to say "it''s not a big deal."', 'Social'),
('Get another player to put on headphones.', 'Social'),
('Get another player to name a historical event.', 'Social'),
('Get another player to say "let''s do it."', 'Social'),
('Get another player to talk about their favorite book.', 'Social'),
('Get another player to say "I can''t wait."', 'Social'),
('Get another player to start a timer or stopwatch.', 'Social'),
('Get another player to name a geometric shape.', 'Social'),
('Get another player to say "I don''t think so."', 'Social'),
('Get another player to talk about their commute.', 'Social'),
('Get another player to say "what are you doing?"', 'Social'),
('Get another player to check the ingredients on a food package.', 'Social'),
('Get another player to name a vegetable.', 'Social'),
('Get another player to say "I''ll try."', 'Social'),
('Get another player to talk about a funny video they saw.', 'Social'),
('Get another player to say "that sounds good."', 'Social'),
('Get another player to search for something in a bag.', 'Social'),
('Get another player to name an insect.', 'Social'),
('Get another player to say "I''m not a fan."', 'Social'),
('Get another player to talk about a political topic.', 'Social'),
('Get another player to say "that''s a shame."', 'Social'),
('Get another player to charge their phone.', 'Social'),
('Get another player to name a type of drink.', 'Social'),
('Get another player to say "I''m not surprised."', 'Social'),
('Get another player to talk about their favorite band or artist.', 'Social'),
('Get another player to say "I guess so."', 'Social'),
('Get another player to pick something up off the floor.', 'Social'),
('Get another player to name a type of shoe.', 'Social'),
('Get another player to say "it is what it is."', 'Social'),
('Get another player to talk about a weird dream.', 'Social'),
('Get another player to say "what''s the plan?"', 'Social'),
('Get another player to use a foreign accent.', 'Social'),
('Get another player to name a part of the human body.', 'Social'),
('Get another player to say "I''m so sorry."', 'Social'),
('Get another player to talk about their first job.', 'Social'),
('Get another player to say "that''s a good one."', 'Social'),
('Get another player to try to fix something that is broken.', 'Social'),
('Get another player to say a word that starts with the letter ''P''.', 'Social'),
('Get another player to say "I need help."', 'Social'),
('Get another player to talk about their favorite holiday.', 'Social'),
('Get another player to say "are you sure?"', 'Social'),
('Get another player to shuffle a deck of cards.', 'Social'),
('Get another player to name a type of pasta.', 'Social'),
('Get another player to say "I don''t get it."', 'Social'),
('Get another player to talk about something they regret.', 'Social'),
('Get another player to say "that''s adorable."', 'Social'),
('Get another player to turn a light on or off.', 'Social'),
('Get another player to name a type of dog.', 'Social'),
('Get another player to say "I''m out of here."', 'Social'),
('Get another player to talk about a favorite teacher.', 'Social'),
('Get another player to say "I''ll take it."', 'Social'),
('Get another player to say the alphabet.', 'Social'),
('Get another player to name a type of candy.', 'Social'),
('Get another player to say "I don''t remember."', 'Social'),
('Get another player to talk about their favorite app.', 'Social'),
('Get another player to say "that''s a good idea."', 'Social'),
('Get another player to look under a table.', 'Social'),
('Get another player to name a Disney character.', 'Social'),
('Get another player to say "I''m not in the mood."', 'Social'),
('Get another player to talk about a childhood memory.', 'Social'),
('Get another player to say "you first."', 'Social'),
('Get another player to use a remote control.', 'Social'),
('Get another player to name a type of fish.', 'Social'),
('Get another player to say "I don''t believe you."', 'Social'),
('Get another player to talk about their best friend.', 'Social'),
('Get another player to say "that''s my favorite."', 'Social'),
('Get another player to close a window or door.', 'Social'),
('Get another player to name a type of weather phenomenon.', 'Social'),
('Get another player to say "I''m working on it."', 'Social'),
('Get another player to talk about a conspiracy theory.', 'Social'),
('Get another player to say "I''ll think about it."', 'Social'),
('Get another player to do a coin toss.', 'Social'),
('Get another player to name a famous scientist.', 'Social'),
('Get another player to say "I have a question."', 'Social'),
('Get another player to talk about their exercise routine.', 'Social'),
('Get another player to say "that''s a relief."', 'Social'),
('Get another player to compare two things.', 'Social'),
('Get another player to name a piece of art.', 'Social'),
('Get another player to say "I''m freezing."', 'Social'),
('Get another player to talk about a viral trend.', 'Social'),
('Get another player to say "I''m all ears."', 'Social'),
('Get another player to look at a map.', 'Social'),
('Get another player to name a famous author.', 'Social'),
('Get another player to say "that''s a tough one."', 'Social'),
('Get another player to talk about their biggest accomplishment.', 'Social'),
('Get another player to say "I''m so happy for you."', 'Social'),
('Get another player to count objects in a room.', 'Social'),
('Get another player to name a famous building.', 'Social'),
('Get another player to say "I need a break."', 'Social'),
('Get another player to talk about something they are grateful for.', 'Social'),
('Get another player to say "you''re a lifesaver."', 'Social'),
('Get another player to play rock-paper-scissors with you.', 'Social'),
('Get another player to name a type of vehicle.', 'Social'),
('Get another player to say "that''s my jam."', 'Social'),
('Get another player to talk about their favorite restaurant.', 'Social'),
('Get another player to say "I''m sweating."', 'Social'),
('Get another player to try to read your mind.', 'Social'),
('Get another player to name a type of fabric.', 'Social'),
('Get another player to say "I can''t complain."', 'Social'),
('Get another player to talk about a public figure.', 'Social'),
('Get another player to say "that''s hilarious."', 'Social'),
('Get another player to open a jar or bottle for you.', 'Social'),
('Get another player to name a type of jewelry.', 'Social'),
('Get another player to say "I''m not going to lie."', 'Social'),
('Get another player to talk about their favorite scent.', 'Social'),
('Get another player to say "that''s the spirit."', 'Social'),
('Get another player to look at their reflection.', 'Social'),
('Get another player to name a constellation.', 'Social'),
('Get another player to say "I''m dead." (as a figure of speech)', 'Social'),
('Get another player to talk about their favorite childhood toy.', 'Social'),
('Get another player to say "you''re the best."', 'Social'),
('Get another player to try to balance something on their finger.', 'Social'),
('Get another player to say a type of sauce.', 'Social'),
('Get another player to say "I need coffee."', 'Social'),
('Get another player to talk about their favorite TV show.', 'Social'),
('Get another player to say "that''s a classic."', 'Social'),
('Get another player to try to say a tongue twister.', 'Social'),
('Get another player to name a social media platform.', 'Social'),
('Get another player to say "I''ll pass."', 'Social'),
('Get another player to talk about a memorable gift they received.', 'Social'),
('Get another player to say "that''s understandable."', 'Social'),
('Get another player to untangle a cord or string.', 'Social'),
('Get another player to name a type of soup.', 'Social'),
('Get another player to say "I''m starving."', 'Social'),
('Get another player to talk about their favorite color.', 'Social'),
('Get another player to say "that''s the goal."', 'Social'),
('Get another player to make a shadow puppet.', 'Social'),
('Get another player to name a type of nut.', 'Social'),
('Get another player to say "I''m speechless."', 'Social'),
('Get another player to talk about their favorite place in the world.', 'Social'),
('Get another player to say "you''ve got to be kidding."', 'Social'),
('Get another player to write their name down.', 'Social'),
('Get another player to name a brand of cereal.', 'Social'),
('Get another player to say "I''ll be there."', 'Social'),
('Get another player to talk about a secret they have.', 'Social'),
('Get another player to say "that''s my cue."', 'Social'),
('Get another player to try to whistle with their fingers.', 'Social'),
('Get another player to name a famous artist.', 'Social'),
('Get another player to say "I''m not picky."', 'Social'),
('Get another player to talk about a time they were embarrassed.', 'Social'),
('Get another player to say "that''s for sure."', 'Social'),
('Get another player to organize a small pile of items.', 'Social'),
('Get another player to name a type of hat.', 'Social'),
('Get another player to say "I''m impressed."', 'Social'),
('Get another player to talk about their family traditions.', 'Social'),
('Get another player to say "you read my mind."', 'Social'),
('Get another player to make an animal sound.', 'Social'),
('Get another player to name a type of spice.', 'Social'),
('Get another player to say "I''m all set."', 'Social'),
('Get another player to talk about a skill they want to learn.', 'Social'),
('Get another player to say "that''s the dream."', 'Social'),
('Get another player to check if they have something in their teeth.', 'Social'),
('Get another player to name a famous activist.', 'Social'),
('Get another player to say "I can''t."', 'Social'),
('Get another player to talk about their favorite comedian.', 'Social'),
('Get another player to say "you''re hilarious."', 'Social'),
('Get another player to build a small tower out of objects.', 'Social'),
('Get another player to name a type of bread.', 'Social'),
('Get another player to say "I''m so over it."', 'Social'),
('Get another player to talk about a strange food they''ve eaten.', 'Social'),
('Get another player to say "that''s the truth."', 'Social'),
('Get another player to look at the sky and comment on the clouds.', 'Social'),
('Get another player to name a famous inventor.', 'Social'),
('Get another player to say "I can relate."', 'Social'),
('Get another player to talk about their favorite holiday movie.', 'Social'),
('Get another player to say "you get what I''m saying?"', 'Social'),
('Get another player to perform a simple magic trick.', 'Social'),
('Get another player to name a type of beer or wine.', 'Social'),
('Get another player to say "I''m not a morning person."', 'Social'),
('Get another player to talk about a cause they support.', 'Social'),
('Get another player to say "that''s a bold move."', 'Social'),
('Get another player to look for a specific object in the room.', 'Social'),
('Get another player to name a famous athlete.', 'Social'),
('Get another player to say "I''m on the fence."', 'Social'),
('Get another player to talk about their favorite thing about themselves.', 'Social'),
('Get another player to say "you nailed it."', 'Social'),
('Get another player to try to speak in a low or high-pitched voice.', 'Social'),
('Get another player to name a type of tea.', 'Social'),
('Get another player to say "I''m so confused."', 'Social'),
('Get another player to talk about a recurring dream.', 'Social'),
('Get another player to say "that''s a good memory."', 'Social'),
('Get another player to demonstrate a dance move.', 'Social'),
('Get another player to say a word that rhymes with "blue".', 'Social'),
('Get another player to say "let me check."', 'Social'),
('Get another player to talk about a piece of technology they can''t live without.', 'Social'),
('Get another player to say "that''s the way to do it."', 'Social'),
('Get another player to try to guess a song you''re humming.', 'Social'),
('Get another player to name a type of farm animal.', 'Social'),
('Get another player to say "I''m not so sure about that."', 'Social'),
('Get another player to talk about their morning coffee routine.', 'Social'),
('Get another player to say "you''re a genius."', 'Social'),
('Get another player to try to juggle.', 'Social'),
('Get another player to name a type of pizza topping.', 'Social'),
('Get another player to say "I''m going crazy."', 'Social'),
('Get another player to talk about a time they got lost.', 'Social'),
('Get another player to say "that''s a good sign."', 'Social'),
('Get another player to tell you the day''s date.', 'Social'),
('Get another player to name a famous director.', 'Social'),
('Get another player to say "I''m in a good mood."', 'Social'),
('Get another player to talk about their favorite podcast.', 'Social'),
('Get another player to say "you''re making me blush."', 'Social'),
('Get another player to try to pat their head and rub their stomach.', 'Social'),
('Get another player to name a type of ocean animal.', 'Social'),
('Get another player to say "I need a vacation."', 'Social'),
('Get another player to talk about their favorite season and why.', 'Social'),
('Get another player to say "that''s a game changer."', 'Social'),
('Get another player to tell you which way is North.', 'Social'),
('Get another player to name a character from a classic book.', 'Social'),
('Get another player to say "I''m not worried."', 'Social'),
('Get another player to talk about their favorite type of weather.', 'Social'),
('Get another player to say "you''re on fire."', 'Social'),
('Get another player to try to estimate the length of an object.', 'Social'),
('Get another player to name a type of cookie.', 'Social'),
('Get another player to say "I''m just saying."', 'Social'),
('Get another player to talk about a road trip they''ve taken.', 'Social'),
('Get another player to say "that''s a good way to put it."', 'Social'),
('Get another player to make a paper airplane.', 'Social'),
('Get another player to say a word with four syllables.', 'Social'),
('Get another player to say "I''m trying my best."', 'Social'),
('Get another player to talk about their favorite board game.', 'Social'),
('Get another player to say "that''s out of my control."', 'Social'),
('Get another player to try to name all the players in the game.', 'Social'),
('Get another player to name a type of mountain.', 'Social'),
('Get another player to say "I''m not a fan of that."', 'Social'),
('Get another player to talk about a time they were very lucky.', 'Social'),
('Get another player to say "that''s the whole point."', 'Social'),
('Get another player to try to wink with both eyes.', 'Social'),
('Get another player to name a part of a car.', 'Social'),
('Get another player to say "I''m feeling lucky."', 'Social'),
('Get another player to talk about their favorite YouTuber.', 'Social'),
('Get another player to say "you''ve got a point."', 'Social'),
('Get another player to try to remember a specific date.', 'Social'),
('Get another player to name a type of river.', 'Social'),
('Get another player to say "I''m not complaining."', 'Social'),
('Get another player to talk about a movie that made them cry.', 'Social'),
('Get another player to say "that''s a different story."', 'Social'),
('Get another player to try to impersonate another player.', 'Social'),
('Get another player to name a brand of clothing.', 'Social'),
('Get another player to say "I''m taking a break."', 'Social'),
('Get another player to talk about a food they want to try.', 'Social'),
('Get another player to say "that''s a great question."', 'Social'),
('Get another player to try to identify a smell with their eyes closed.', 'Social'),
('Get another player to name a famous painting.', 'Social'),
('Get another player to say "I''m not convinced."', 'Social'),
('Get another player to talk about a concert they''ve been to.', 'Social'),
('Get another player to say "you''re too kind."', 'Social'),
('Get another player to try to say "red leather, yellow leather" five times fast.', 'Social'),
('Get another player to name a type of house.', 'Social'),
('Get another player to say "I''m running on empty."', 'Social'),
('Get another player to talk about their favorite dessert.', 'Social'),
('Get another player to say "that''s a nice thought."', 'Social'),
('Get another player to try to guess your middle name.', 'Social'),
('Get another player to name a famous philosopher.', 'Social'),
('Get another player to say "I''m not ready for this."', 'Social'),
('Get another player to talk about a memorable meal.', 'Social'),
('Get another player to say "you''re my hero."', 'Social'),
('Get another player to try to make a noise using only their mouth.', 'Social'),
('Get another player to name a type of bridge.', 'Social'),
('Get another player to say "I''m not the one to ask."', 'Social'),
('Get another player to talk about a piece of good advice they received.', 'Social'),
('Get another player to say "that''s a weight off my shoulders."', 'Social'),
('Get another player to try to guess your favorite color.', 'Social'),
('Get another player to name a famous poem.', 'Social'),
('Get another player to say "I''m not judging."', 'Social'),
('Get another player to talk about a time they helped someone.', 'Social'),
('Get another player to say "you''re a good sport."', 'Social'),
('Get another player to try to fold a t-shirt perfectly.', 'Social'),
('Get another player to say a type of sandwich.', 'Social'),
('Get another player to say "I''m having a great time."', 'Social'),
('Get another player to talk about their favorite place to relax.', 'Social'),
('Get another player to say "that''s a pleasant surprise."', 'Social'),
('Get another player to try to identify a song from its first second.', 'Social'),
('Get another player to name a type of musical genre.', 'Social'),
('Get another player to say "I''m not going anywhere."', 'Social'),
('Get another player to talk about a subject they know a lot about.', 'Social'),
('Get another player to say "you''re in my thoughts."', 'Social'),
('Get another player to try to hold their breath for 20 seconds.', 'Social'),
('Get another player to name a type of currency.', 'Social'),
('Get another player to say "I''m keeping my options open."', 'Social'),
('Get another player to talk about their favorite cartoon.', 'Social'),
('Get another player to say "that''s a work of art."', 'Social'),
('Get another player to try to find a four-leaf clover.', 'Social'),
('Get another player to name a type of cloud.', 'Social'),
('Get another player to say "I''m not making any promises."', 'Social'),
('Get another player to talk about a weird food combination they like.', 'Social'),
('Get another player to say "you''re asking the right person."', 'Social'),
('Get another player to try to remember their first memory.', 'Social'),
('Get another player to name a type of dance.', 'Social'),
('Get another player to say "I''m having deja vu."', 'Social'),
('Get another player to talk about a favorite family recipe.', 'Social'),
('Get another player to say "that''s a blast from the past."', 'Social'),
('Get another player to try to estimate the temperature.', 'Social'),
('Get another player to say the name of a US state.', 'Social'),
('Get another player to say "I''m not a robot" and mean it.', 'Social'),
('Get another player to talk about a time they faced a fear.', 'Social'),
('Get another player to say "you''re on the right track."', 'Social'),
('Get another player to try to say a difficult name correctly.', 'Social'),
('Get another player to name a famous historical battle.', 'Social'),
('Get another player to say "I''m not a people person."', 'Social'),
('Get another player to talk about a good deed they did.', 'Social'),
('Get another player to say "that''s the best I can do."', 'Social'),
('Get another player to try to tell a story without using the word "the".', 'Social'),
('Get another player to name a type of government.', 'Social'),
('Get another player to say "I''m not holding my breath."', 'Social'),
('Get another player to talk about a funny misunderstanding.', 'Social'),
('Get another player to say "you''ve made my day."', 'Social'),
('Get another player to try to name five things that are blue.', 'Social'),
('Get another player to name a famous scientist''s discovery.', 'Social'),
('Get another player to say "I''m not one to gossip, but..."', 'Social'),
('Get another player to talk about a favorite childhood book.', 'Social'),
('Get another player to say "that''s a beautiful thing."', 'Social'),
('Get another player to try to come up with a team name for the group.', 'Social'),
('Get another player to name a type of building material.', 'Social'),
('Get another player to say "I''m not going to argue."', 'Social'),
('Get another player to talk about a personal mantra or philosophy.', 'Social'),
('Get another player to say "you''re a natural."', 'Social'),
('Get another player to try to remember what they ate for breakfast.', 'Social'),
('Get another player to say the name of an ocean.', 'Social'),
('Get another player to say "I''m not a fan of surprises."', 'Social'),
('Get another player to talk about a project they are proud of.', 'Social'),
('Get another player to say "that''s a sign."', 'Social'),
('Get another player to try to find a specific word in a book.', 'Social'),
('Get another player to name a famous speech.', 'Social'),
('Get another player to say "I''m not in a rush."', 'Social'),
('Get another player to talk about a time they felt powerful.', 'Social'),
('Get another player to say "you''re an inspiration."', 'Social'),
('Get another player to try to guess a password you made up.', 'Social'),
('Get another player to name a type of reptile.', 'Social'),
('Get another player to say "I''m not giving up."', 'Social'),
('Get another player to talk about their favorite smell.', 'Social'),
('Get another player to say "that''s a deal."', 'Social'),
('Get another player to try to create a new handshake with you.', 'Social'),
('Get another player to name a famous explorer.', 'Social'),
('Get another player to say "I''m not superstitious."', 'Social'),
('Get another player to talk about a time they were completely wrong.', 'Social'),
('Get another player to say "you''re a true friend."', 'Social'),
('Get another player to try to draw a perfect circle.', 'Social'),
('Get another player to say the name of a jungle animal.', 'Social'),
('Get another player to say "I''m not in control."', 'Social'),
('Get another player to talk about a place they want to visit.', 'Social'),
('Get another player to say "that''s a good thing to know."', 'Social'),
('Get another player to try to guess the last movie you watched.', 'Social'),
('Get another player to name a type of rock or mineral.', 'Social'),
('Get another player to say "I''m not in the mood for games." (The irony!)', 'Social'),
('Get another player to talk about a time they got lucky.', 'Social'),
('Get another player to say "you''re on a roll."', 'Social'),
('Get another player to try to tell a lie and a truth, and have you guess.', 'Social'),
('Get another player to name a famous politician.', 'Social'),
('Get another player to say "I''m not looking for trouble."', 'Social'),
('Get another player to talk about a favorite photograph they have.', 'Social'),
('Get another player to say "that''s a load off my mind."', 'Social'),
('Get another player to try to say the months of the year backwards.', 'Social'),
('Get another player to name a famous landmark they''ve visited.', 'Social'),
('Get another player to say "I''m not going to say anything."', 'Social'),
('Get another player to talk about a favorite piece of clothing they own.', 'Social'),
('Get another player to say "you''re a mind reader."', 'Social'),
('Get another player to try to build a house of cards.', 'Social'),
('Get another player to say the name of a desert animal.', 'Social'),
('Get another player to say "I''m not taking sides."', 'Social'),
('Get another player to talk about a time they were proud of someone else.', 'Social'),
('Get another player to say "that''s a question for the ages."', 'Social'),
('Get another player to try to guess what''s in your pocket.', 'Social'),
('Get another player to name a famous revolutionary.', 'Social'),
('Get another player to say "I''m not trying to be difficult."', 'Social'),
('Get another player to talk about a favorite TV show from their childhood.', 'Social'),
('Get another player to say "you''re full of surprises."', 'Social'),
('Get another player to try to remember a phone number by heart.', 'Social'),
('Get another player to name a type of weather storm.', 'Social'),
('Get another player to say "I''m not that kind of person."', 'Social'),
('Get another player to talk about a time they learned a valuable lesson.', 'Social'),
('Get another player to say "that''s a wrap."', 'Social'),
('Get another player to try to make a rhyme with your name.', 'Social'),
('Get another player to name a famous king or queen.', 'Social'),
('Get another player to say "I''m not the boss."', 'Social'),
('Get another player to talk about their favorite way to spend a rainy day.', 'Social'),
('Get another player to say "you''re a legend."', 'Social'),
('Get another player to try to find the North Star.', 'Social'),
('Get another player to name a type of body organ.', 'Social'),
('Get another player to say "I''m not made of money."', 'Social'),
('Get another player to talk about a time they felt truly happy.', 'Social'),
('Get another player to say "that''s a work in progress."', 'Social'),
('Get another player to try to find a specific shape in the clouds.', 'Social'),
('Get another player to name a famous battle.', 'Social'),
('Get another player to say "I''m not interested."', 'Social'),
('Get another player to talk about a time they overcame an obstacle.', 'Social'),
('Get another player to say "you''re the only one who gets it."', 'Social'),
('Get another player to try to name every other player''s favorite color.', 'Social'),
('Get another player to name a type of fish you can eat.', 'Social'),
('Get another player to say "I''m not in charge."', 'Social'),
('Get another player to talk about a time they felt brave.', 'Social'),
('Get another player to say "that''s above my pay grade."', 'Social'),
('Get another player to try to guess the meaning of an obscure word.', 'Social'),
('Get another player to name a famous queen.', 'Social'),
('Get another player to say "I''m not a threat."', 'Social'),
('Get another player to talk about their favorite thing about the current season.', 'Social'),
('Get another player to say "you''re a sight for sore eyes."', 'Social'),
('Get another player to try to write with their non-dominant hand.', 'Social'),
('Get another player to name a famous novel.', 'Social'),
('Get another player to say "I''m not looking forward to it."', 'Social'),
('Get another player to talk about a moment that changed their life.', 'Social'),
('Get another player to say "that''s a good way to be."', 'Social'),
('Get another player to try to tell time by the sun.', 'Social'),
('Get another player to name a famous play.', 'Social'),
('Get another player to say "I''m not moving."', 'Social'),
('Get another player to talk about a time they made a big mistake.', 'Social'),
('Get another player to say "you''re one of a kind."', 'Social'),
('Get another player to try to guess the year a coin was minted.', 'Social'),
('Get another player to name a famous composer.', 'Social'),
('Get another player to say "I''m not a role model."', 'Social'),
('Get another player to talk about a time they felt understood.', 'Social'),
('Get another player to say "that''s all I''m saying."', 'Social'),
('Get another player to try to find a specific constellation.', 'Social'),
('Get another player to name a famous sculptor.', 'Social'),
('Get another player to say "I''m not a fortune teller."', 'Social'),
('Get another player to talk about a favorite memory with their family.', 'Social'),
('Get another player to say "you''re a miracle worker."', 'Social'),
('Get another player to try to identify a brand by its logo alone.', 'Social');
